# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI名称：部署云函数
上：
  工作流调度：
  时间表：
    - cron：'50 */4 * * * '
  观看：
    类型：开始
  存储库调度：
    类型：deploy_tencent_scf
工作：
  构建：
    运行：ubuntu-latest
    如果：github.event.repository.owner.id == github.event.sender.id
    环境：
      TZ :亚洲/上海
      JD_COOKIE : ${{ 秘密.JD_COOKIE}}
      JD_DEBUG : ${{ 秘密.JD_DEBUG}}
      JD_USER_AGENT : ${{ 秘密.JD_USER_AGENT}}
      TENCENTSCF_SOURCE_TYPE : ${{ secrets.TENCENTSCF_SOURCE_TYPE}}
      TENCENTSCF_SOURCE_URL : ${{ secrets.TENCENTSCF_SOURCE_URL}}
      TENCENTSCF_MEMORYSIZE : ${{ secrets.TENCENTSCF_MEMORYSIZE}}
      PUSH_KEY : ${{ secrets.PUSH_KEY}}
      BARK_PUSH : ${{ 秘密.BARK_PUSH}}
      BARK_SOUND : ${{ 秘密.BARK_SOUND}}
      TG_BOT_TOKEN : ${{ 秘密.TG_BOT_TOKEN}}
      TG_USER_ID : ${{ 秘密.TG_USER_ID}}
      DD_BOT_TOKEN : ${{ 秘密.DD_BOT_TOKEN}}
      DD_BOT_SECRET : ${{ 秘密.DD_BOT_SECRET}}
      QYWX_KEY : ${{ 秘密.QYWX_KEY}}
      QYWX_AM : ${{ 秘密.QYWX_AM}}
      IGOT_PUSH_KEY : ${{ 秘密.IGOT_PUSH_KEY}}
      PUSH_PLUS_TOKEN : ${{ 秘密.PUSH_PLUS_TOKEN}}
      PUSH_PLUS_USER : ${{ 秘密.PUSH_PLUS_USER}}
      TG_PROXY_HOST : ${{ 秘密.TG_PROXY_HOST}}
      TG_PROXY_PORT : ${{ 秘密.TG_PROXY_PORT}}
      TG_PROXY_AUTH : ${{ 秘密.TG_PROXY_AUTH}}
      TG_API_HOST : ${{ secrets.TG_API_HOST}}
      FRUITSHARECODES : ${{ secrets.FRUITSHARECODES}}
      PETSHARECODES : ${{ secrets.PETSHARECODES}}
      PLANT_BEAN_SHARECODES : ${{ secrets.PLANT_BEAN_SHARECODES}}
      DDFACTORY_SHARECODES : ${{ 秘密.DDFACTORY_SHARECODES}}
      DREAM_FACTORY_SHARE_CODES：${{ secrets.DREAM_FACTORY_SHARE_CODES}}
      JDZZ_SHARECODES : ${{ 秘密.JDZZ_SHARECODES}}
      JDJOY_SHARECODES : ${{ 秘密.JDJOY_SHARECODES}}
      BOOKSHOP_SHARECODES : ${{ secrets.BOOKSHOP_SHARECODES}}
      JD_CASH_SHARECODES : ${{ 秘密.JD_CASH_SHARECODES}}
      JXNC_SHARECODES : ${{ 秘密.JXNC_SHARECODES}}
      JDSGMH_SHARECODES : ${{ 秘密.JDSGMH_SHARECODES}}
      JDCFD_SHARECODES : ${{ 秘密.JDCFD_SHARECODES }}
      JD818_SHARECODES : ${{ 秘密.JD818_SHARECODES}}
      JD_BEAN_STOP : ${{ 秘密.JD_BEAN_STOP}}
      JD_BEAN_SIGN_STOP_NOTIFY : ${{ 秘密.JD_BEAN_SIGN_STOP_NOTIFY}}
      JD_BEAN_SIGN_NOTIFY_SIMPLE：${{ secrets.JD_BEAN_SIGN_NOTIFY_SIMPLE}}
      PET_NOTIFY_CONTROL : ${{ 秘密.PET_NOTIFY_CONTROL}}
      FRUIT_NOTIFY_CONTROL : ${{ 秘密.FRUIT_NOTIFY_CONTROL}}
      CASH_NOTIFY_CONTROL : ${{ 秘密.CASH_NOTIFY_CONTROL}}
      DDQ_NOTIFY_CONTROL : ${{ 秘密.DDQ_NOTIFY_CONTROL}}
      JDZZ_NOTIFY_CONTROL : ${{ 秘密.JDZZ_NOTIFY_CONTROL}}
      JD_JOY_REWARD_NOTIFY : ${{ 秘密.JD_JOY_REWARD_NOTIFY}}
      JOY_FEED_COUNT : ${{ 秘密.JOY_FEED_COUNT}}
      JOY_HELP_FEED : ${{ 秘密.JOY_HELP_FEED}}
      JOY_RUN_FLAG : ${{ 秘密.JOY_RUN_FLAG}}
      JOY_TEAM_LEVEL : ${{ 秘密.JOY_TEAM_LEVEL}}
      JOY_RUN_NOTIFY : ${{ 秘密.JOY_RUN_NOTIFY}}
      JOY_RUN_HELP_MYSELF : ${{ 秘密.JOY_RUN_HELP_MYSELF}}
      JD_JOY_REWARD_NAME : ${{ 秘密.JD_JOY_REWARD_NAME}}
      MARKET_COIN_TO_BEANS：${{ secrets.MARKET_COIN_TO_BEANS}}
      MARKET_REWARD_NOTIFY : ${{ secrets.MARKET_REWARD_NOTIFY}}
      JOIN_PK_TEAM : ${{ 秘密.JOIN_PK_TEAM}}
      SUPERMARKET_LOTTERY : ${{ secrets.SUPERMARKET_LOTTERY}}
      FRUIT_BEAN_CARD : ${{ 秘密.FRUIT_BEAN_CARD}}
      UN_SUBSCRIBES : ${{ secrets.UN_SUBSCRIBES}}
      JDJOY_HELPSELF : ${{ 秘密.JDJOY_HELPSELF}}
      JDJOY_APPLYJDBEAN : ${{ 秘密.JDJOY_APPLYJDBEAN}}
      BUY_JOY_LEVEL : ${{ 秘密.BUY_JOY_LEVEL}}
      MONEY_TREE_SELL_FRUIT：${{ secrets.MONEY_TREE_SELL_FRUIT}}
      FACTORAY_WANTPRODUCT_NAME：${{ secrets.FACTORAY_WANTPRODUCT_NAME}}
      DREAMFACTORY_FORBID_ACCOUNT : ${{ 秘密.DREAMFACTORY_FORBID_ACCOUNT}}
      JDFACTORY_FORBID_ACCOUNT : ${{ 秘密.JDFACTORY_FORBID_ACCOUNT}}
      CFD_NOTIFY_CONTROL : ${{ 秘密.CFD_NOTIFY_CONTROL}}
      JD_JXD_EXCHANGE : ${{ 秘密.JD_JXD_EXCHANGE}}
      DYJ_PACKETID : ${{ 秘密.DYJ_PACKETID}}
      MONEYTREE_SHARECODES：${{ secrets.MONEYTREE_SHARECODES}}
      dyjCode : ${{ secrets.dyjCode}}
      JD_TRY : ${{ 秘密.JD_TRY}}
      TYT_PACKETID : ${{ 秘密.TYT_PACKETID}}
      JD_JOY_PARK : ${{ 秘密.JD_JOY_PARK}}
      HELPAUTHOR_WXJ : ${{ 秘密.HELPAUTHOR_WXJ}}
      JXNC_NOTIFY_LEVEL : ${{ 秘密.JXNC_NOTIFY_LEVEL}}
      summer_movement_ShHelpFlag : ${{ secrets.summer_movement_ShHelpFlag}}
      FS_LEVEL : ${{ 秘密.FS_LEVEL}}
      EXJXBEANS : ${{ 秘密.EXJXBEANS}}
    步骤：
      -名称：结帐
        用途：actions/checkout@v2
        与：
          存储库：${{ github.repository }}

      -名称：使用 Node.js ${{ matrix.node-version }}
        使用：操作/设置节点@v1
        与：
          节点版本：${{ matrix.node-version }}

      -名称：“安装依赖”
        运行：|
          npm 安装
          npm 安装得到
          npm 安装坚韧的饼干
          npm 安装 js-yaml
          npm 安装承诺
          npm 安装 png-js
      -名称：“将Secrets里面配置的变量添加到severless.yml里面作为环境变量”
        运行：|
          如果 [ $TZ ]; 然后 sed -i "/variables/a\ TZ: $TZ" serverless.yml; 菲
          如果 [ $JD_COOKIE ]; 然后 sed -i "/variables/a\ JD_COOKIE: $JD_COOKIE" serverless.yml; 菲;
          如果 [ $JD_DEBUG ]; 然后 sed -i "/variables/a\ JD_DEBUG: $JD_DEBUG" serverless.yml; 菲;
          如果 [ $JD_USER_AGENT ]; 然后 sed -i "/variables/a\ JD_USER_AGENT: $JD_USER_AGENT" serverless.yml; 菲;
          如果 [ $TENCENTSCF_SOURCE_TYPE ]; 然后 sed -i "/variables/a\TENCENTSCF_SOURCE_TYPE: $TENCENTSCF_SOURCE_TYPE" serverless.yml; 菲;
          如果 [ $TENCENTSCF_SOURCE_URL ]; 然后 sed -i "/variables/a\ TENCENTSCF_SOURCE_URL: $TENCENTSCF_SOURCE_URL" serverless.yml; 菲;
          如果 [ $PUSH_KEY ]; 然后 sed -i "/variables/a\ PUSH_KEY: $PUSH_KEY" serverless.yml; 菲;
          如果 [ $BARK_PUSH ]; 然后 sed -i "/variables/a\ BARK_PUSH: $BARK_PUSH" serverless.yml; 菲;
          如果 [ $BARK_SOUND ]; 然后 sed -i "/variables/a\ BARK_SOUND: $BARK_SOUND" serverless.yml; 菲;
          如果 [ $TG_BOT_TOKEN ]; 然后 sed -i "/variables/a\ TG_BOT_TOKEN: $TG_BOT_TOKEN" serverless.yml; 菲;
          如果 [ $TG_USER_ID ]; 然后 sed -i "/variables/a\ TG_USER_ID: $TG_USER_ID" serverless.yml; 菲;
          如果 [ $DD_BOT_TOKEN ]; 然后 sed -i "/variables/a\ DD_BOT_TOKEN: $DD_BOT_TOKEN" serverless.yml; 菲;
          如果 [ $DD_BOT_SECRET ]; 然后 sed -i "/variables/a\ DD_BOT_SECRET: $DD_BOT_SECRET" serverless.yml; 菲;
          如果 [ $QYWX_KEY ]; 然后 sed -i "/variables/a\ QYWX_KEY: $QYWX_KEY" serverless.yml; 菲;
          如果 [ $QYWX_AM ]; 然后 sed -i "/variables/a\ QYWX_AM: $QYWX_AM" serverless.yml; 菲;
          如果 [ $IGOT_PUSH_KEY ]; 然后 sed -i "/variables/a\ IGOT_PUSH_KEY: $IGOT_PUSH_KEY" serverless.yml; 菲;
          如果 [ $PUSH_PLUS_TOKEN ]; 然后 sed -i "/variables/a\ PUSH_PLUS_TOKEN: $PUSH_PLUS_TOKEN" serverless.yml; 菲;
          如果 [ $PUSH_PLUS_USER ]; 然后 sed -i "/variables/a\ PUSH_PLUS_USER: $PUSH_PLUS_USER" serverless.yml; 菲;
          如果 [ $TG_PROXY_HOST ]; 然后 sed -i "/variables/a\ TG_PROXY_HOST: $TG_PROXY_HOST" serverless.yml; 菲;
          如果 [ $TG_PROXY_PORT ]; 然后 sed -i "/variables/a\ TG_PROXY_PORT: $TG_PROXY_PORT" serverless.yml; 菲;
          如果 [ $TG_PROXY_AUTH ]; 然后 sed -i "/variables/a\ TG_PROXY_AUTH: $TG_PROXY_AUTH" serverless.yml; 菲;
          如果 [ $TG_API_HOST ]; 然后 sed -i "/variables/a\ TG_API_HOST: $TG_API_HOST" serverless.yml; 菲;
          如果 [ $FRUITSHARECODES ]; 然后 sed -i "/variables/a\ FRUITSHARECODES: $FRUITSHARECODES" serverless.yml; 菲;
          如果 [ $PETSHARECODES ]; 然后 sed -i "/variables/a\ PETSHARECODES: $PETSHARECODES" serverless.yml; 菲;
          如果 [ $PLANT_BEAN_SHARECODES ]; 然后 sed -i "/variables/a\ PLANT_BEAN_SHARECODES: $PLANT_BEAN_SHARECODES" serverless.yml; 菲;
          如果 [ $DDFACTORY_SHARECODES ]; 然后 sed -i "/variables/a\ DDFACTORY_SHARECODES: $DDFACTORY_SHARECODES" serverless.yml; 菲;
          如果 [ $DREAM_FACTORY_SHARE_CODES ]; 然后 sed -i "/variables/a\ DREAM_FACTORY_SHARE_CODES: $DREAM_FACTORY_SHARE_CODES" serverless.yml; 菲;
          如果 [ $JDZZ_SHARECODES ]; 然后 sed -i "/variables/a\ JDZZ_SHARECODES: $JDZZ_SHARECODES" serverless.yml; 菲;
          如果 [ $JDJOY_SHARECODES ]; 然后 sed -i "/variables/a\ JDJOY_SHARECODES: $JDJOY_SHARECODES" serverless.yml; 菲;
          如果 [ $BOOKSHOP_SHARECODES ]; 然后 sed -i "/variables/a\ BOOKSHOP_SHARECODES: $BOOKSHOP_SHARECODES" serverless.yml; 菲;
          如果 [ $JD_CASH_SHARECODES ]; 然后 sed -i "/variables/a\ JD_CASH_SHARECODES: $JD_CASH_SHARECODES" serverless.yml; 菲;
          如果 [ $JXNC_SHARECODES ]; 然后 sed -i "/variables/a\ JXNC_SHARECODES: $JXNC_SHARECODES" serverless.yml; 菲;
          如果 [ $JDSGMH_SHARECODES ]; 然后 sed -i "/variables/a\ JDSGMH_SHARECODES: $JDSGMH_SHARECODES" serverless.yml; 菲;
          如果 [ $JDCFD_SHARECODES ]; 然后 sed -i "/variables/a\ JDCFD_SHARECODES: $JDCFD_SHARECODES" serverless.yml; 菲;
          如果 [ $JD818_SHARECODES ]; 然后 sed -i "/variables/a\ JD818_SHARECODES: $JD818_SHARECODES" serverless.yml; 菲;
          如果 [ $JD_BEAN_STOP ]; 然后 sed -i "/variables/a\ JD_BEAN_STOP: $JD_BEAN_STOP" serverless.yml; 菲;
          如果 [ $JD_BEAN_SIGN_STOP_NOTIFY ]; 然后 sed -i "/variables/a\ JD_BEAN_SIGN_STOP_NOTIFY: $JD_BEAN_SIGN_STOP_NOTIFY" serverless.yml; 菲;
          如果 [ $JD_BEAN_SIGN_NOTIFY_SIMPLE ]; 然后 sed -i "/variables/a\ JD_BEAN_SIGN_NOTIFY_SIMPLE: $JD_BEAN_SIGN_NOTIFY_SIMPLE" serverless.yml; 菲;
          如果 [ $PET_NOTIFY_CONTROL ]; 然后 sed -i "/variables/a\ PET_NOTIFY_CONTROL: $PET_NOTIFY_CONTROL" serverless.yml; 菲;
          如果 [ $FRUIT_NOTIFY_CONTROL ]; 然后 sed -i "/variables/a\ FRUIT_NOTIFY_CONTROL: $FRUIT_NOTIFY_CONTROL" serverless.yml; 菲;
          如果 [ $CASH_NOTIFY_CONTROL ]; 然后 sed -i "/variables/a\ CASH_NOTIFY_CONTROL: $CASH_NOTIFY_CONTROL" serverless.yml; 菲;
          如果 [ $DDQ_NOTIFY_CONTROL ]; 然后 sed -i "/variables/a\ DDQ_NOTIFY_CONTROL: $DDQ_NOTIFY_CONTROL" serverless.yml; 菲;
          如果 [ $JDZZ_NOTIFY_CONTROL ]; 然后 sed -i "/variables/a\ JDZZ_NOTIFY_CONTROL: $JDZZ_NOTIFY_CONTROL" serverless.yml; 菲;
          如果 [ $JD_JOY_REWARD_NOTIFY ]; 然后 sed -i "/variables/a\ JD_JOY_REWARD_NOTIFY: $JD_JOY_REWARD_NOTIFY" serverless.yml; 菲;
          如果 [ $JOY_FEED_COUNT ]; 然后 sed -i "/variables/a\ JOY_FEED_COUNT: $JOY_FEED_COUNT" serverless.yml; 菲;
          如果 [ $JOY_HELP_FEED ]; 然后 sed -i "/variables/a\ JOY_HELP_FEED: $JOY_HELP_FEED" serverless.yml; 菲;
          如果 [ $JOY_RUN_FLAG ]; 然后 sed -i "/variables/a\ JOY_RUN_FLAG: $JOY_RUN_FLAG" serverless.yml; 菲;
          如果 [ $JOY_TEAM_LEVEL ]; 然后 sed -i "/variables/a\ JOY_TEAM_LEVEL: $JOY_TEAM_LEVEL" serverless.yml; 菲;
          如果 [ $JOY_RUN_NOTIFY ]; 然后 sed -i "/variables/a\ JOY_RUN_NOTIFY: $JOY_RUN_NOTIFY" serverless.yml; 菲;
          如果 [ $JOY_RUN_HELP_MYSELF ]; 然后 sed -i "/variables/a\ JOY_RUN_HELP_MYSELF: $JOY_RUN_HELP_MYSELF" serverless.yml; 菲;
          如果 [ $JD_JOY_REWARD_NAME ]; 然后 sed -i "/variables/a\ JD_JOY_REWARD_NAME: $JD_JOY_REWARD_NAME" serverless.yml; 菲;
          如果 [ $MARKET_COIN_TO_BEANS ]; 然后 sed -i "/variables/a\ MARKET_COIN_TO_BEANS: $MARKET_COIN_TO_BEANS" serverless.yml; 菲;
          如果 [ $MARKET_REWARD_NOTIFY ]; 然后 sed -i "/variables/a\ MARKET_REWARD_NOTIFY: $MARKET_REWARD_NOTIFY" serverless.yml; 菲;
          如果 [ $JOIN_PK_TEAM ]; 然后 sed -i "/variables/a\ JOIN_PK_TEAM: $JOIN_PK_TEAM" serverless.yml; 菲;
          如果 [ $SUPERMARKET_LOTTERY ]; 然后 sed -i "/variables/a\ SUPERMARKET_LOTTERY: $SUPERMARKET_LOTTERY" serverless.yml; 菲;
          如果 [ $FRUIT_BEAN_CARD ]; 然后 sed -i "/variables/a\ FRUIT_BEAN_CARD: $FRUIT_BEAN_CARD" serverless.yml; 菲;
          如果 [ $UN_SUBSCRIBES ]; 然后 sed -i "/variables/a\ UN_SUBSCRIBES: $UN_SUBSCRIBES" serverless.yml; 菲;
          如果 [ $JDJOY_HELPSELF ]; 然后 sed -i "/variables/a\ JDJOY_HELPSELF: $JDJOY_HELPSELF" serverless.yml; 菲;
          如果 [ $JDJOY_APPLYJDBEAN ]; 然后 sed -i "/variables/a\ JDJOY_APPLYJDBEAN: $JDJOY_APPLYJDBEAN" serverless.yml; 菲;
          如果 [ $BUY_JOY_LEVEL ]; 然后 sed -i "/variables/a\ BUY_JOY_LEVEL: $BUY_JOY_LEVEL" serverless.yml; 菲;
          如果 [ $MONEY_TREE_SELL_FRUIT ]; 然后 sed -i "/variables/a\ MONEY_TREE_SELL_FRUIT: $MONEY_TREE_SELL_FRUIT" serverless.yml; 菲;
          如果 [ $FACTORAY_WANTPRODUCT_NAME ]; 然后 sed -i "/variables/a\ FACTORAY_WANTPRODUCT_NAME: $FACTORAY_WANTPRODUCT_NAME" serverless.yml; 菲;
          如果 [ $DREAMFACTORY_FORBID_ACCOUNT ]; 然后 sed -i "/variables/a\ DREAMFACTORY_FORBID_ACCOUNT: $DREAMFACTORY_FORBID_ACCOUNT" serverless.yml; 菲;
          如果 [ $JDFACTORY_FORBID_ACCOUNT ]; 然后 sed -i "/variables/a\ JDFACTORY_FORBID_ACCOUNT: $JDFACTORY_FORBID_ACCOUNT" serverless.yml; 菲;
          如果 [ $CFD_NOTIFY_CONTROL ]; 然后 sed -i "/variables/a\ CFD_NOTIFY_CONTROL: $CFD_NOTIFY_CONTROL" serverless.yml; 菲;
          如果 [ $JD_JXD_EXCHANGE ]; 然后 sed -i "/variables/a\ JD_JXD_EXCHANGE: $JD_JXD_EXCHANGE" serverless.yml; 菲;
          如果 [ $JXNC_NOTIFY_LEVEL ]; 然后 sed -i "/variables/a\ JXNC_NOTIFY_LEVEL: $JXNC_NOTIFY_LEVEL" serverless.yml; 菲;
          如果 [ $dyjCode ]; 然后 sed -i "/variables/a\ dyjCode: $dyjCode" serverless.yml; 菲;
          如果 [ $DYJ_PACKETID ]; 然后 sed -i "/variables/a\ DYJ_PACKETID: $DYJ_PACKETID" serverless.yml; 菲;
          如果 [ $MONEYTREE_SHARECODES ]; 然后 sed -i "/variables/a\ MONEYTREE_SHARECODES: $MONEYTREE_SHARECODES" serverless.yml; 菲;
          如果 [ $JD_TRY ]; 然后 sed -i "/variables/a\ JD_TRY: $JD_TRY" serverless.yml; 菲;
          如果 [ $TYT_PACKETID ]; 然后 sed -i "/variables/a\ TYT_PACKETID: $TYT_PACKETID" serverless.yml; 菲;
          如果 [ $JD_JOY_PARK ]; 然后 sed -i "/variables/a\ JD_JOY_PARK: $JD_JOY_PARK" serverless.yml; 菲;
          如果 [ $HELPAUTHOR_WXJ ]; 然后 sed -i "/variables/a\ HELPAUTHOR_WXJ: $HELPAUTHOR_WXJ" serverless.yml; 菲;
          如果 [ $summer_movement_ShHelpFlag ]; 然后 sed -i "/variables/a\ summer_movement_ShHelpFlag: $summer_movement_ShHelpFlag" serverless.yml; 菲;
          如果 [ $FS_LEVEL ]; 然后 sed -i "/variables/a\ FS_LEVEL: $FS_LEVEL" serverless.yml; 菲;
          如果 [ $EXJXBEANS ]; 然后 sed -i "/variables/a\ EXJXBEANS: $EXJXBEANS" serverless.yml; 菲;
          猫无服务器.yml
          环境
      - name : "压缩文件夹"
        运行：zip -r myfile.zip ./*

      -名称：“安装依赖”
        运行：|
          npm 安装
          npm 安装tencentcloud-sdk-nodejs
      -名称：“部署到腾讯云函数”
        运行：节点tencentscf.js
        环境：
          阶段：开发
          SERVERLESS_PLATFORM_VENDOR：腾讯
          TENCENT_SECRET_ID : ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY : ${{ 秘密.TENCENT_SECRET_KEY }}
          TENENT_REGION : ${{ secrets.SCF_REGION }}
          TENCENT_FUNCTION_NAME : ${{ 秘密.TENCENT_FUNCTION_NAME }}
          TENCENT_MemorySize : ${{ secrets.TENCENT_MemorySize }}
        
      -名称：《部署失败通知》
        运行：节点 action.js
